article/urls.py
from django.urls import path

from . import views

app_name = 'article'

urlpatterns =[
    path('article-list/',views.article_list,name = 'article_list'),
    path('article-detail/<int:id>/',views.article_detail,name = 'article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
    path('article-update/<int:id>/', views.article_update, name='article_update'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/',include('article.urls',namespace= 'article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
]

urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/',include('article.urls',namespace= 'article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
]

userprofile/urls.py
from django.urls import path

from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/',views.user_logout,name = 'logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

templates/back_to_top_func.html
<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100;"></button>

<script>
    // 向上滚动的函数
    $(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({scrollTop: 0}, 500);
        });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BackTop').fadeIn(300);
            } else {
                $('#BackTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>

<style>
    /* 按钮边框的大小、位置、样式 */
    .toTop-arrow {
        width: 3.5rem;
        height: 7.0rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.7;
        background: transparent;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    /* 绘制按钮中的向上箭头 */
    .toTop-arrow::before, .toTop-arrow::after {
        width: 31px;
        height: 7px;
        border-radius: 3px;
        background: black;
        position: absolute;
        content: "";
    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;
    }

    /* 取消点击按钮时的聚焦 */
    .toTop-arrow:focus {
        outline: none;
    }
</style>

templates/base.html
{% load staticfiles %}
<html lang="zh-cn">

<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
</head>

<body>
    {% include 'header.html' %}
    <div id="wrapper">
        {% block content %}{% endblock content %}
        <div id="push"></div>
    </div>
    {% include 'footer.html' %}
    <script src="{% static 'jquery/jquery-3.4.1.js' %}"></script>
    <script src="{% static 'popper/popper-1.15.0.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'layer/layer.js' %}"></script>
    {% include 'back_to_top_func.html' %}

    <style>
        html, body {
            height: 100%;
            margin: 0;
        }

        #wrapper {
            min-height: 100%;
            margin-bottom: -60px;
        }

        #footer,
        #push {
            height: 60px;
        }
    </style>
</body>

</html>

templates/footer.html
{% load staticfiles %}
<div>
    <br><br><br>
</div>
<footer class="py-3  bg-dark" id="footer">
    <div class="container">
        <p class="m-0 text-center text-white"> 0 </p>
    </div>
</footer>

templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="#">我的博客</a>
    <div>
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'article:article_create' %}">写文章</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'article:article_list' %}">文章</a>
        </li>

        {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ user.username }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href='{% url "userprofile:edit" user.id %}'>个人信息</a>
              <a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a>
              <a class="dropdown-item" href='{% url "userprofile:logout" %}'>退出登录</a>
            </div>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'userprofile:login' %}">登录</a>
          </li>
        {% endif %}

      </ul>
    </div>

  </div>
</nav>

{% if user.is_authenticated %}
<form
    style="display:none;"
    id="user_delete"
    action="{% url 'userprofile:delete' user.id %}"
    method="POST"
>
{% csrf_token %}
    <button type="submit">发送</button>
</form>
    <script>
        function user_delete() {
            layer.open({
                title: "确认删除",
                content: "确认删除用户资料吗？",
                yes: function(index, layero) {
                    $('form#user_delete button').click();
                    layer.close(index);
                },
            })
        }
    </script>
{% endif %}