article/urls.py
from django.urls import path

from . import views

app_name = 'article'

urlpatterns =[
    path('article-list/',views.article_list,name = 'article_list'),
    path('article-detail/<int:id>/',views.article_detail,name = 'article_detail'),
    path('article-create/', views.article_create, name='article_create'),
    path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
    path('article-update/<int:id>/', views.article_update, name='article_update'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/',include('article.urls',namespace= 'article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
]

urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/',include('article.urls',namespace= 'article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
]

article/models.py
from django.contrib.auth.models import User
from django.db import models
from taggit.managers import TaggableManager
# Create your models here.
from django.utils import timezone

class ArticleColumn(models.Model):
    title = models.CharField(max_length=100,blank = True)
    created = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.title

class ArticlePost(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    body = models.TextField()
    total_views = models.PositiveIntegerField(default=0)
    column = models.ForeignKey(
        ArticleColumn,
        null = True,
        blank = True,
        on_delete=models.CASCADE,
        related_name='article',
    )
    tags = TaggableManager(blank=True)
    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title

article/forms.py
from django import forms

from .models import ArticlePost


class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ('title','body','tags')

article/views.py
import markdown
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from .forms import ArticlePostForm
from .models import ArticlePost


def article_list(request):
    tag = request.GET.get('tag')
    order = request.GET.get('order')

    article_list = ArticlePost.objects.all()

    if tag and tag != 'None':
        article_list = article_list.filter(tags__name__in=[tag])

    if order == 'total_views':
        article_list = article_list.order_by('-total_views')


    paginator = Paginator(article_list,10)
    page = request.GET.get('page')
    articles = paginator.get_page(page)
    context = { 'articles': articles,
                'order': order,
                'tag': tag,}
    return render(request, 'article/list.html', context)

def article_detail(request,id):
    article = ArticlePost.objects.get(id = id)
    article.total_views += 1
    article.save(update_fields=['total_views'])

    md = markdown.Markdown(
        extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ])
    article.body = md.convert(article.body)
    context = {'article':article,'toc':md.toc}
    return render(request,'article/detail.html',context)

@login_required(login_url='/userprofile/login/')
def article_create(request):
    if request.method == 'POST':
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            new_article = article_post_form.save(commit=False)
            new_article.author = User.objects.get(id=request.user.id)
            new_article.save()
            article_post_form.save_m2m()
            return redirect("article:article_list")
        else:
            HttpResponse("ERROR")
    else:
        article_post_form = ArticlePostForm()
        context = { 'article_post_form': article_post_form }
        return render(request,'article/create.html',context)

def article_safe_delete(request,id):
    if request.method == 'POST':
        article = ArticlePost.objects.get(id = id)
        article.delete()
        return redirect("article:article_list")
    else:
        return HttpResponse("ERROR")

@login_required(login_url='/userprofile/login/')
def article_update(request,id):
    article = ArticlePost.objects.get(id=id)

    if request.user != article.author:
        return HttpResponse("抱歉，你无权修改这篇文章。")
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            article.title = request.POST['title']
            article.body = request.POST['body']
            article.save()
            return redirect("article:article_detail", id=id)
        else:
            return HttpResponse("ERROR")
    else:
        article_post_form = ArticlePostForm()
        context = { 'article': article, 'article_post_form': article_post_form }
        return render(request, 'article/update.html', context)

templates/article/create.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 写文章 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <input type="text" class="form-control" id="title" name="title">
                </div>


                <div class="form-group">
                    <label for="tags">标签</label>
                    <input type="text"
                        class="form-control col-3"
                        id="tags"
                        name="tags">
                </div>

                <div class="form-group">
                    <label for="body">文章正文</label>
                    <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/article/detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    文章详情
{% endblock title %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-9">
            <h1 class="mt-4 mb-4">{{ article.title }}</h1>
            <div class="alert alert-success">
            <div>
                作者：{{ article.author }}
                {% if user == article.author %}
                    <a href="#" onclick="confirm_safe_delete()">删除文章</a>
                    <a href="{% url 'article:article_update' article.id %}">编辑文章</a>
                {% endif %}
                <a>views：{{ article.total_views }}</a>
            </div>

            </div>
            <div class="col-12">
            <p>{{ article.body|safe }}</p>
            </div>
        </div>

        <div class="col-3 mt-4">
            <h4><strong>目录</strong></h4>
            <hr>
            <div>
                {{ toc|safe }}
            </div>
        </div>
    </div>
</div>

<form
      style="display:none;"
      id="safe_delete"
      action="{% url 'article:article_safe_delete' article.id %}"
      method="POST"
      >
    {% csrf_token %}
    <button type="submit">发送</button>
</form>

<script>
    function confirm_safe_delete() {
    layer.open({
        title: "确认删除",
        content: "确认删除这篇文章吗？",
        yes: function(index, layero) {
            $('form#safe_delete button').click();
            layer.close(index);
        }
    })
}
</script>

{% endblock content %}

templates/article/list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    首页
{% endblock title %}

{% block content %}

<div class="container">
    <div class="row mt-2">
    {% for article in articles %}
        <div class="col-12">
            <span>
                    {% for tag in article.tags.all %}
                        <a href="{% url 'article:article_list' %}?tag={{ tag }}"
                           class="badge badge-secondary"
                        >
                            {{ tag }}
                        </a>
                    {% endfor %}
                </span>

            <h4>
                <b>
                    <a href="{% url 'article:article_detail' article.id %}"
                       style="color: black;">
                        {{ article.title }}
                    </a>
                </b>
            </h4>
            <div>
                <p style="color: gray;">
                    {{ article.body|slice:'100' }}...
                </p>
            </div>
            <p>
<!--                <span style="color: green;">-->
<!--                    {{ article.total_views }} 浏览&nbsp;&nbsp;&nbsp;-->
<!--                </span>-->
                <span style="color: blue;">
                    {{ article.created|date:'Y-m-d' }} 发布&nbsp;&nbsp;&nbsp;
                </span>
                <span style="color: darkred;">
                    {{ article.updated|date:'Y-m-d' }} 更新
                </span>
            </p>
            <hr>
        </div>
    {% endfor %}
</div>



<div class="pagination row">
    <div class="m-auto">
        <span class="step-links">
            {% if articles.has_previous %}

                <a href="?page={{ articles.previous_page_number }}"
                   class="btn btn-dark"
                >
                    {{ articles.previous_page_number }}
                </a>
            {% endif %}

            <span class="current btn btn-dark btn-lg">
                {{ articles.number }}
            </span>

            {% if articles.has_next %}
                <a href="?page={{ articles.next_page_number }}"
                   class="btn btn-dark"
                >
                    {{ articles.next_page_number }}
                </a>
            {% endif %}
        </span>
    </div>
</div>
</div>
{% endblock content %}

templates/article/update.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 更新文章 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <!-- 在 value 属性中指定文本框的初始值为旧的内容，即 article 对象中的 title 字段 -->
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本域不需要 value 属性，直接在标签体中嵌入数据即可 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}